### ISSUE TITLE
the problem with finding the "blood altar" structure in nether

### ISSUE THREAD

**Issue by badalanchik** [EEEAB/EEEABsMobs#14] opened 2024-09-20 13:34 UTC
when you click on the "blood altar" structure search eye or enter the /locate command to search for a structure, it either crashes from the server or writes that there is no such structure, at the same time, everything is fine with the second structure in the ordinary world. Minecraft version 1.19.2, forge 43.4.0, mod version 0.95

**Comment by EEEAB** [comment] 2024-09-20 14:30
the mod version of the old save file was updated to 0.95 from an older version?

**Comment by badalanchik** [comment] 2024-09-21 05:50
No, it seems

**Comment by EEEAB** [comment] 2024-09-22 15:02
It's quite strange; I encountered this issue during previous tests as well, but now I'm unable to reproduce it. I apologize that I cannot resolve this issue in the short term, and you may need to consider an alternative solution, such as: regenerating the Nether (please consider this option carefully).

**Comment by EEEAB** [comment] 2024-11-05 09:09
The issue has been identified and verified as resolved. It will be fixed in the next version

**Closed as completed** 2024-11-05 09:09 UTC
Labels: compatibility
